language: java
install: true
os:
  - linux
  - osx

jdk:
- oraclejdk8

script:
- ./gradlew check -S --info --console plain

after_success:
- bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master